# Generated by Django 3.2.4 on 2021-06-23 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210623_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='producer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.producers'),
        ),
    ]
