# Generated by Django 3.2.4 on 2021-06-25 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_orderproducts_orders'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderproducts',
            options={'verbose_name': 'OrderProduct', 'verbose_name_plural': 'OrderProducts'},
        ),
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
    ]
